name: Hello world
description: A workflow to say hello
iconName: octicon beaker
creator: me
on:
  push:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: | 
          echo "Hello, world!"