name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
          echo "The current date is $(date)."
          echo "The current time is $(date +%T)." # 24 hour format
          echo "The current DIR is $(pwd)."
          echo "The current BRANCH is $(git branch --show-current)."